name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration (e.g., development, production)'
        required: true
        default: 'development'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            dominikkielkowski/hotel-reservation-web-client:${{ github.event.inputs.configuration }}
          build-args:
            CONFIGURATION: ${{ github.event.inputs.configuration }}
